version: "3"

services:
  database:
    image: postgres:10-alpine # https://hub.docker.com/_/postgres/
    env_file:
    - etc/env/postgres.env
    volumes:
    - etc/postgres/initdb.d:/docker-entrypoint-initdb.d
    - pgdata:/var/lib/postgresql/data

  click-migration:
    image: kamilsk/click:latest # https://hub.docker.com/r/kamilsk/click/
    command: [ "migrate", "up", "--with-demo" ]
    depends_on:
    - database
  click:
    image: kamilsk/click:latest
    command: [ "run", "--with-profiler", "--with-monitoring" ]
    depends_on:
    - click-migration

  forma-migration:
    image: kamilsk/form-api:latest # https://hub.docker.com/r/kamilsk/form-api/
    command: [ "migrate", "up", "--with-demo" ]
    depends_on:
    - database
  forma:
    image: kamilsk/form-api:latest
    command: [ "run", "--with-profiler", "--with-monitoring" ]
    depends_on:
    - forma-migration

  hugo:
    image: kamilsk/hugo:latest # https://hub.docker.com/r/kamilsk/hugo/

  passport-migration:
    image: kamilsk/passport:latest # https://hub.docker.com/r/kamilsk/passport/
    command: [ "migrate", "up" ]
    depends_on:
    - database
  passport:
    image: kamilsk/passport:latest
    command: [ "run", "--with-profiler", "--with-monitoring" ]
    depends_on:
    - passport-migration

  server:
    image: kamilsk/nginx:alpine # https://hub.docker.com/r/kamilsk/nginx/
    depends_on:
    - click
    - forma
    - hugo
    - passport
    env_file:
    - etc/env/balancer.env
    ports:
    - ${HUGS_HTTP_PORT}:80
    - ${HUGS_HTTPS_PORT}:443
    volumes:
    - ssl:/etc/nginx/ssl
    - letsencrypt:/etc/letsencrypt
    - etc/nginx/conf.d:/etc/nginx/sites-available:ro

volumes:

  # {database:
  pgdata: { driver: local }
  # /database}

  # {server:
  ssl:         { driver: local }
  letsencrypt: { driver: local }
  # /server}


# TODO
# - common
#   - env files
# - click
#   - ports
# - forma
#   - ports
# - hugo
#   - ports
#   - volumes
# - passport
#   - ports
