baseURL:        https://hugo.127.0.0.1.xip.io/
metaDataFormat: yaml
theme:          materialkit

author:
  name:     Kamil Samigullin
  homepage: https://kamil.samigullin.info/

disableKinds:               [RSS, taxonomy, taxonomyTerm]
disableLiveReload:          false
disableHugoGeneratorInject: true

enableRobotsTXT: true
googleAnalytics: UA-109817251-25
sitemap:
  changefreq: monthly
  priority:   0.5
  filename:   sitemap.xml

pygmentsCodeFences: true

outputs:
  home:         [HTML]
  page:         [HTML]
  section:      [HTML]
  taxonomy:     [HTML]
  taxonomyTerm: [HTML]

# language fallback

params:
  company: { id: octolab }
  lead:    { id: kamil.samigullin }

  click:
    enabled: true
    proxy:   /goto
    service: https://click.127.0.0.1.xip.io/

  forma:
    enabled: true
    proxy:   /forma
    service: https://forma.127.0.0.1.xip.io/

  passport:
    enabled: true
    proxy:   /passport
    service: https://passport.127.0.0.1.xip.io/

  keywords: [platform, static sites]

  yandexMetrika: 49138258

# language specific

enableMissingTranslationPlaceholders: false

languages:
  en:
    languageCode: en
    weight:       1

    title:     Hugs
    copyright: "[OctoLab](https://www.octolab.ru/) project"

    menu:
      home_footer:
      - identifier: site
        name:       Site
        pre:        <i class="fas fa-home"></i>
        weight:     1
        url:        https://www.octolab.org/
      - identifier: blog
        name:       Blog
        pre:        <i class="far fa-newspaper"></i>
        weight:     2
        url:        https://blog.octolab.org/
      - identifier: idea
        name:       Ideas
        pre:        <i class="far fa-lightbulb"></i>
        weight:     3
        url:        https://idea.octolab.org/

# defaults

defaultContentLanguage:         en
defaultContentLanguageInSubdir: false
defaultExtension:               html
defaultLayout:                  post
