baseURL:        https://hugo.127.0.0.1.xip.io/
metaDataFormat: yaml
theme:          materialkit

author:
  name:     Kamil Samigullin
  homepage: https://kamil.samigullin.info/

disableKinds:               [RSS, taxonomy, taxonomyTerm]
disableLiveReload:          false
disableHugoGeneratorInject: true

enableRobotsTXT: true
googleAnalytics: UA-109817251-25
sitemap:
  changefreq: monthly
  priority:   0.5
  filename:   sitemap.xml

pygmentsCodeFences: true

outputs:
  home:         [HTML]
  page:         [HTML]
  section:      [HTML]
  taxonomy:     [HTML]
  taxonomyTerm: [HTML]

# language fallback

params:
  company: { id: octolab }
  lead:    { id: kamil.samigullin }

  click:
    enabled: true
    proxy:   /goto
    live:    https://click.127.0.0.1.xip.io

  forma:
    enabled: true
    proxy:   /forma
    live:    https://forma.127.0.0.1.xip.io

  keywords: [platform, static sites]

# language specific

enableMissingTranslationPlaceholders: false

languages:
  en:
    languageCode: en
    weight:       1

    title:     Hugs
    copyright: "[OctoLab](https://www.octolab.ru/) project"

# defaults

defaultContentLanguage:         en
defaultContentLanguageInSubdir: false
defaultExtension:               html
defaultLayout:                  post
